### ISSUE TITLE
ERRO when using Textdetection.py 

### ISSUE THREAD

**Issue by munideepak** [opencv/opencv_contrib#1407] opened 2017-10-13 10:46 UTC
File "textdetection.py", line 27, in <module>
    channels = cv2.text.computeNMChannels(img)
AttributeError: 'module' object has no attribute 'computeNMChannels'

**Comment by munideepak** [comment] 2017-10-13 10:47
Can anybody here please helpout

**Comment by berak** [comment] 2017-10-16 12:53
opencv3.1 indeed did not [have this function](https://github.com/opencv/opencv_contrib/blame/3584d3c27fb91a6101afb323805d6a49e49b37eb/modules/text/include/opencv2/text/erfilter.hpp#L262).

not a bug, just an outdated cv2 on your box. please try to update to latest master

**Comment by munideepak** [comment] 2017-10-16 13:06
Oo thanx were can i get that latest master

**Comment by berak** [comment] 2017-10-16 13:13
best idea is still, [to build from src](https://github.com/opencv/opencv_contrib/blob/master/README.md)

(from the way you ask, i guess, you did *not* do that the last time ..)

then: 

    pip install opencv-contrib-python

*might* install 3.3, but it also *will* lack gui or video file support on linux/mac

**Comment by munideepak** [comment] 2017-10-16 16:09
cmake -DOPENCV_EXTRA_MODULES_PATH=<opencv_contrib>/modules <opencv_source_directory>
 can you please tell me how I can find opencv_source_directory?

**Comment by berak** [comment] 2017-10-17 05:27
please understand, that this is the wrong place for a "install the python bindings" tutorial

(this is the library bug tracker, and you don't have a bug)

kindly close this issue, we'll help you with the install from http://answers.opencv.org

**Closed** 2017-10-30 08:27 UTC
Labels: question (invalid)
