### ISSUE TITLE
OpenCV cuda bindings for python seem receive wrong param types for `cudawarping/src/warp.cpp`

### ISSUE THREAD

**Issue by MiaoDX** [opencv/opencv_contrib#2393] opened 2019-12-18 03:19 UTC
##### System information (version)

- OpenCV => 4.1
- Operating System / Platform => Linux Ubuntu 16.04 64 Bit (Nvidia Xavier)
- CUDA => 10.x 

- OpenCV => OpenCV cuda bindings for python seem receive wrong param types for [cudawarping/src/warp.cpp](https://github.com/opencv/opencv_contrib/blob/4.1.2/modules/cudawarping/src/warp.cpp).

##### Detailed description

The parameter `M` for `warpAffine`, `buildWarpAffineMaps`, `warpPerspective`, `buildWarpPerspectiveMaps` is all defined as cv::Mat? 
However, in python binding, they are expected as `cv.cuda_GpuMat`. (ohterwise `TypeError: Expected Ptr<cv::UMat> for argument '%s'` will be raised).
However, pass `cuda_GpuMat` will trigger error at [Mat M = _M.getMat();](https://github.com/opencv/opencv_contrib/blob/4.1.2/modules/cudawarping/src/warp.cpp#L82) with `xxx/opencv/modules/core/src/matrix_wrap.cpp:118: error: (-213:The function/feature is not implemented) You should explicitly call download method for cuda::GpuMat object in function 'getMat_'`

##### Steps to reproduce

 ```python
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
#
# Demo usage of cuda.warpAffine from OpenCV 4.x

import cv2 as cv
import numpy as np

mask = np.random.randint(low=100, high=255, size=(1000, 2000)).astype(np.uint8)
mapping = np.array([[1.0, 0.0, 400.0], [0.0, 1.0, 300.0]])

image_container = cv.cuda_GpuMat()
mapping_container = cv.cuda_GpuMat()
dsize = (100, 200)
stream = cv.cuda_Stream()

image_container.upload(mask)
mapping_container.upload(mapping)

crop_mask = cv.cuda.warpAffine(src=image_container,
                               M=mapping_container,
                               dsize=dsize,
                               flags=cv.WARP_INVERSE_MAP,
                               stream=stream).download()

cv.imshow('CropMask', crop_mask)
cv.waitKey()

```

##### Possible solutions

I am not so familiar with `InputArray` as once-for-all param type, so, maybe this can be some easy fix for you guys. Currently, I replace `Mat M = _M.getMat();` to `Mat M;  _M.download(M);` to make python happy (and will break cpp codes..)
Another gossip, the cuda version seems no good than CPU version -.-

**Comment by cudawarped** [comment] 2019-12-22 11:08
Hi,
Try adding the changes in opencv/opencv_contrib#2396 to see if this resolves your problem.
For usage see this [notebook ](https://github.com/cudawarped/opencv-experiments/blob/master/nbs/cudawarping.ipynb)where I get around 2 orders of magnitude speed up over the CPU version (Mobile RTX 2080 vs 17-8700) on a 4K video.

**Comment by perrywang** [comment] 2020-01-14 09:42
same problem when using python binding cv2.cuda.warpPerspective

**Comment by cudawarped** [comment] 2020-01-14 09:47
> same problem when using python binding cv2.cuda.warpPerspective

is that with the changes in #2396 ?

**Comment by perrywang** [comment] 2020-01-14 10:01
> > same problem when using python binding cv2.cuda.warpPerspective
> 
> is that with the changes in #2396 ?

Yes! Expect merge. I will port fix at local if it will take a little bit long wait time.

**Comment by perrywang** [comment] 2020-01-15 08:56
@cudawarped I ported fix at local and test still error happend. Below is my simple test function
TypeError: Expected Ptr<cv::UMat> for argument '%s'

`import cv2
import numpy as np


img = cv2.imread("1.jpg")
img_shape = (img.shape[1], img.shape[0])

img_cuda = cv2.cuda_GpuMat()
img_cuda.upload(img)

matrix = np.array([3, 3])
matrix_cuda = cv2.cuda_GpuMat()
matrix_cuda.upload(matrix)

cv2.cuda.warpPerspective(img_cuda, matrix_cuda, img_shape)`

**Comment by cudawarped** [comment] 2020-01-15 09:28
@perrywang 

I should have mentioned earlier that fix will not work if M is a `GpuMat` since in C++ the transform matrix can only be a `Mat`.   This should probably be in the documentation.

Currently it does not make sense for `M` to be a `GpuMat`, since internally it is `Mat` and using a `GpuMat` will add the overhead of downloading and blocking on the host, if as suggested above you called
`_M.download(M);`
That is unless you have changed the internals to use a `GpuMat` without the need to transfer to the host?

With the modification in #2396 the tests in [test_cudawarping.py](https://github.com/opencv/opencv_contrib/blob/d1a0ee1db33679e1a19e47b72cb1a9038e8101a2/modules/cudawarping/misc/python/test/test_cudawarping.py#L60) pass locally for me.

**Comment by perrywang** [comment] 2020-01-15 09:58
@cudawarped Got it! Many thanks!!! We are misunderstanding this method usage.

**Comment by nievesbrunet** [comment] 2021-04-20 20:13
@perrywang were you able to solve the error? I am getting the same: 
`TypeError: Expected Ptrcv::UMat for argument '%s'`
Thanks!

**Comment by mkarzhaubayeva** [comment] 2022-05-18 06:35
@nievesbrunet were you able to resolve this? `TypeError: Expected Ptrcv::UMat for argument '%s'`

**Comment by cudawarped** [comment] 2022-05-18 10:18
> @nievesbrunet were you able to resolve this? `TypeError: Expected Ptrcv::UMat for argument '%s'`

Are you using the latest version of OpenCV?  If so can you check your arguments are correct by comparing with [test_cudawarping.py](https://github.com/opencv/opencv_contrib/blob/4.x/modules/cudawarping/misc/python/test/test_cudawarping.py)?

**Comment by nievesbrunet** [comment] 2022-05-18 12:16
@mkarzhaubayeva unfortunately I didn't get it to work

**Comment by cudawarped** [comment] 2022-05-18 12:43
> @mkarzhaubayeva unfortunately I didn't get it to work

Can you remember which version of OpenCV you were using and if you were using the correct arguments?  For instance passing M as a GpuMat will result in the error you mentioned?

**Comment by cudawarped** [comment] 2022-06-03 14:21
@alalek as test_cudawarping.py is passing without issue and if @nievesbrunet and/or @mkarzhaubayeva don't have a reproducable example of how this is failing on the master branch should we close this issue?

**Closed** 2022-06-04 18:56 UTC
Labels: category: cuda, incomplete, category: python bindings
