### ISSUE TITLE
BUG ‘WARP_RELATIVE_MAP’ was not declared

### ISSUE THREAD

**Issue by yibinzhang97** [opencv/opencv_contrib#3810] opened 2024-10-16 03:56 UTC
##### System information (version)
- OpenCV => 4.7
- Operating System / Platform => arm64
- Compiler => gcc 9.5.0  g++9.5.0
- 
![20241016115421](https://github.com/user-attachments/assets/1bfaaf82-edea-41e9-91f5-c61125b5f0b9)

##### Detailed description

I am compiling OpenCV4.7 using Jetson Orin NX and encountering an error：
[ 38%] Built target opencv_cudaimgproc
[ 39%] Built target opencv_perf_cudaimgproc
Consolidate compiler generated dependencies of target opencv_cudawarping
[ 39%] Building CXX object modules/cudawarping/CMakeFiles/opencv_cudawarping.dir/src/remap.cpp.o
/home/zmofly/tools/opencv47/opencv_contrib/modules/cudawarping/src/remap.cpp: In function ‘void cv::cuda::remap(cv::InputArray, cv::OutputArray, cv::InputArray, cv::InputArray, int, int, cv::Scalar, cv::cuda::Stream&)’:
/home/zmofly/tools/opencv47/opencv_contrib/modules/cudawarping/src/remap.cpp:65:52: error: ‘WARP_RELATIVE_MAP’ was not declared in this scope
   65 |     const bool hasRelativeFlag = ((interpolation & WARP_RELATIVE_MAP) != 0);
      |                                                    ^~~~~~~~~~~~~~~~~
make[2]: *** [modules/cudawarping/CMakeFiles/opencv_cudawarping.dir/build.make:1757：modules/cudawarping/CMakeFiles/opencv_cudawarping.dir/src/remap.cpp.o] 

##### Steps to reproduce
Cmake ： cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -D CUDA_ARCH_BIN=8.7 -D CUDA_ARCH_PTX=8.7 -D OPENCV_GENERATE_PKGCONFIG=YES -D BUILD_opencv_python3=OFF -D WITH_TBB=ON -D WITH_VTK=ON -D WITH_FFMPEG=ON -D WITH_LIBV4L=ON -D WITH_GTK=ON -D WITH_OPENGL=ON -D WITH_ZLIB=ON -D BUILD_PNG=ON -D BUILD_JPEG=ON -D BUILD_TIFF=ON -D WITH_CUDA=ON -D WITH_CUDNN=ON -D WITH_OPENCL=ON -D ENABLE_FAST_MATH=ON -D CUDA_FAST_MATH=ON -D BUILD_TESTS=OFF -D BUILD_JAVA=ON -D BUILD_opencv_world=OFF ..

How should I get out of it? ﻿

**Comment by cudawarped** [comment] 2024-10-16 08:19
@yibinzhang97 Can you also close this as it is a duplicate of https://github.com/opencv/opencv/issues/26312

**Comment by yibinzhang97** [comment] 2024-10-17 08:49
> @yibinzhang97 Can you also close this as it is a duplicate of [opencv/opencv#26312](https://github.com/opencv/opencv/issues/26312)

ok

**Closed** 2024-10-17 08:49 UTC
