### ISSUE TITLE
Cannot build opencv3.4 with opencv_contrib

### ISSUE THREAD

**Issue by utc1205** [opencv/opencv_contrib#1821] opened 2018-10-09 09:36 UTC
##### System information (version)

**I use cmake-gui to build opencv_contrib,
the source code folder : /home/lpc/Downloads/opencv-3.4.0
the build binaries folder : /home/lpc/Downloads/opencv-3.4.0/build
 then i point the "Configure" button , the log file shows below :
anyone meets this situation?** 

Looking for ccache - not found
Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found suitable version "1.2.8", minimum required is "1.2.3") 
Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
Found OpenEXR: /usr/lib/x86_64-linux-gnu/libIlmImf.so
Checking for module 'gtk+-3.0'
  No package 'gtk+-3.0' found
Checking for module 'gstreamer-base-1.0'
  No package 'gstreamer-base-1.0' found
Checking for module 'gstreamer-video-1.0'
  No package 'gstreamer-video-1.0' found
Checking for module 'gstreamer-app-1.0'
  No package 'gstreamer-app-1.0' found
Checking for module 'gstreamer-riff-1.0'
  No package 'gstreamer-riff-1.0' found
Checking for module 'gstreamer-pbutils-1.0'
  No package 'gstreamer-pbutils-1.0' found
Checking for module 'gstreamer-base-0.10'
  No package 'gstreamer-base-0.10' found
Checking for module 'gstreamer-video-0.10'
  No package 'gstreamer-video-0.10' found
Checking for module 'gstreamer-app-0.10'
  No package 'gstreamer-app-0.10' found
Checking for module 'gstreamer-riff-0.10'
  No package 'gstreamer-riff-0.10' found
Checking for module 'gstreamer-pbutils-0.10'
  No package 'gstreamer-pbutils-0.10' found
Looking for linux/videodev.h
Looking for linux/videodev.h - not found
Looking for linux/videodev2.h
Looking for linux/videodev2.h - found
Looking for sys/videoio.h
Looking for sys/videoio.h - not found
Checking for module 'libavresample'
  No package 'libavresample' found
Checking for module 'libgphoto2'
  No package 'libgphoto2' found
found Intel IPP (ICV version): 2017.0.3 [2017.0.3]
at: /home/lpc/Downloads/opencv-3.4.0/build/3rdparty/ippicv/ippicv_lnx
found Intel IPP IW sources: 2017.0.3
at: /home/lpc/Downloads/opencv-3.4.0/build/3rdparty/ippicv/ippiw_lnx
CUDA detected: 8.0
CUDA NVCC target flags: -gencode;arch=compute_20,code=sm_20;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-D_FORCE_INLINES
Found OpenBLAS libraries: /usr/lib/libopenblas.so
Found OpenBLAS include: /usr/include/openblas
LAPACK(OpenBLAS): LAPACK_LIBRARIES: /usr/lib/libopenblas.so
CMake Warning at cmake/OpenCVFindLAPACK.cmake:29 (message):
  LAPACK(OpenBLAS): CBLAS/LAPACK headers are not found in
  '/usr/include/openblas'
Call Stack (most recent call first):
  cmake/OpenCVFindLAPACK.cmake:97 (ocv_lapack_check)
  CMakeLists.txt:604 (include)

Could NOT find Atlas (missing:  Atlas_CLAPACK_INCLUDE_DIR) 
A library with BLAS API found.
A library with LAPACK API found.
Found VTK 7.1.0 (/usr/local/lib/cmake/vtk-7.1/UseVTK.cmake)
CMake Error at cmake/OpenCVModule.cmake:273 (message):
  **The directory /home/lpc/Downloads/opencv-3.4.0/modules is observed for
  OpenCV modules second time.
Call Stack (most recent call first):
  modules/CMakeLists.txt:7 (ocv_glob_modules)**

Configuring incomplete, errors occurred!
See also "/home/lpc/Downloads/opencv-3.4.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/lpc/Downloads/opencv-3.4.0/build/CMakeFiles/CMakeError.log".

**Comment by huzz** [comment] 2018-10-09 12:32
what was the cmake command you used?

**Comment by berak** [comment] 2018-10-09 13:00
hello, @utc1205 ,

you accidentally pointed  `OPENCV_EXTRA_MODULES_PATH` to `/home/lpc/Downloads/opencv-3.4.0/modules` , not to `/home/lpc/Downloads/opencv_contrib-3.4.0/modules`

also note, that [3.4.0](https://github.com/opencv/opencv/releases/tag/3.4.0) is a quite outdated *release*, while you probably wanted the current [3.4 branch](https://github.com/opencv/opencv/tree/3.4) for both.

again it's not a bug, but a user error, so please kindly close this issue.

we can also help you much better with further problems from http://answers.opencv.org/questions/

**Closed** 2018-10-10 01:07 UTC
Labels: duplicate, question (invalid)
