### ISSUE TITLE
compile error 2872 with test_hdr.ccp line 34

### ISSUE THREAD

**Issue by jcjumley** [opencv/opencv_contrib#1947] opened 2018-12-19 14:05 UTC
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by jcjumley** [comment] 2018-12-19 14:44
* Lenova laptop ACPI x64 based PC
*Open CV cloned from this repository (opencv_contrib-master.zip) 12/16/2018
* Windows 10.0.17134 Build 17134
* Cmake 3.13.2 GUI
* Visual Studio Microsoft Visual Studio Community 2017  
Version 15.9.4VisualStudio.15.Release/15.9.4+28307.22215.9.4
Discription of problem:
5 compile errors in test_hdr.ccp e.g. ambigious reference to TonmapDuarand in line 34. I tried adding xphoro:: reference:
Steps to reproduce: see Readme instructions above then open OpenCV.sln in VC and build ALL_Build
I had compiler options Debug and win32 set

**Comment by alalek** [comment] 2018-12-19 17:38
duplicate of this invalid issue #1945

**Closed by alalek** 2018-12-19 17:38 UTC
Labels: duplicate, invalid
