### ISSUE TITLE
DNN module build failed with PROTOBUF_UPDATE_FILES 

### ISSUE THREAD

**Issue by smartnet-club** [opencv/opencv_contrib#2408] opened 2020-01-13 21:47 UTC
- OpenCV => 4.2.0
- Operating System / Platform => Linux acer 4.15.0-74-generic #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Compiler => gcc (Ubuntu 6.5.0-2ubuntu1~16.04) 6.5.0 20181026

##### Detailed description
error: opencv-caffe.pb.h not found

##### Steps to reproduce
build with:
-DWITH_PROTOBUF:BOOL=ON
-DBUILD_PROTOBUF:BOOL=FALSE
-DPROTOBUF_UPDATE_FILES:BOOL=ON
-DOPENCV_DNN_EXTERNAL_PROTOBUF:BOOL=ON

**to fix**
in dnn/CMakeLists.txt

file(GLOB proto_files "${CMAKE_CURRENT_LIST_DIR}/src/tensorflow/*.proto" "${CMAKE_CURRENT_LIST_DIR}/src/caffe/opencv-caffe.proto" "${CMAKE_CURRENT_LIST_DIR}/src/onnx/opencv-onnx.proto")
set(PROTOBUF_GENERATE_CPP_APPEND_PATH ON) # required for tensorflow
protobuf_generate_cpp(fw_srcs fw_hdrs ${proto_files})
**set(fw_inc "${CMAKE_CURRENT_BINARY_DIR}/src/caffe" "${CMAKE_CURRENT_BINARY_DIR}/src/tensorflow" "${CMAKE_CURRENT_BINARY_DIR}/src/onnx")**

**Comment by alalek** [comment] 2020-01-14 00:36
> -DBUILD_PROTOBUF:BOOL=FALSE
-DPROTOBUF_UPDATE_FILES:BOOL=ON

Not compatible set of values (misused).

Valid parameters values are (should work always):
- [default](https://github.com/opencv/opencv/blob/3.4.9/cmake/OpenCVFindProtobuf.cmake#L9-L10): `-DBUILD_PROTOBUF=ON -DPROTOBUF_UPDATE_FILES=OFF`
- or upgrade mode: `-DBUILD_PROTOBUF=OFF -DPROTOBUF_UPDATE_FILES=ON`

This set of values is non reliable (you must have the same protobuf version as builtin OpenCV - unlikely)
- `-DBUILD_PROTOBUF=OFF -DPROTOBUF_UPDATE_FILES=OFF`

---

duplicate of https://github.com/opencv/opencv/issues/16312

**Comment by smartnet-club** [comment] 2020-01-14 05:07
default Protobuf  versions of latest OpenCV and latest Tensorflow are incompatible.

**Comment by alalek** [comment] 2020-01-14 07:44
So, which error message is observed?

**Comment by smartnet-club** [comment] 2020-01-14 09:19
opencv-caffe.pb.h not found
It needs to specify include path to generated files

**Comment by alalek** [comment] 2020-01-14 12:21
> default
> opencv-caffe.pb.h not found

Please recheck that [this code](https://github.com/opencv/opencv/blob/4.2.0/modules/dnn/CMakeLists.txt#L79) has been executed in "default" configuration (`PROTOBUF_UPDATE_FILES=OFF`).

If so, then dump complete failed compiler command line parameters and its output (`make VERBOSE=1` should help).

**Comment by smartnet-club** [comment] 2020-01-14 15:41
If I set PROTOBUF_UPDATE_FILES=OFF the error will be `This file was generated by an older version of protoc` because I use external newer version of Protobuf (v3.11.2)
I've already patched [code](https://github.com/opencv/opencv/blob/4.2.0/modules/dnn/CMakeLists.txt#L79) by `set(fw_inc "${CMAKE_CURRENT_BINARY_DIR}/src/caffe" "${CMAKE_CURRENT_BINARY_DIR}/src/tensorflow" "${CMAKE_CURRENT_BINARY_DIR}/src/onnx")` and finished work. So can't make complete dump.

**Comment by smartnet-club** [comment] 2020-01-14 16:01
The error also in [protobuf-config.cmake](https://github.com/protocolbuffers/protobuf/blob/master/cmake/protobuf-config.cmake.in)

They set `list(APPEND _generated_srcs "${protobuf_generate_PROTOC_OUT_DIR}/${_rel_dir}/${_basename}${_ext}")`
but generate into `ARGS --${protobuf_generate_LANGUAGE}_out ${_dll_export_decl}${protobuf_generate_PROTOC_OUT_DIR} ${_protobuf_include_path} ${_abs_file}`

See [this](https://github.com/protocolbuffers/protobuf/issues/7090#issue-549170470)

**Closed** 2020-06-20 10:48 UTC
Labels: duplicate, invalid
