### ISSUE TITLE
reconstruct was not declared in this scope

### ISSUE THREAD

**Issue by ASif2660** [opencv/opencv_contrib#782] opened 2016-09-20 10:01 UTC
I have been trying to run the recon2v.cpp of the sfm library. When I compile an error is thrown on my screen. Any help would be appreciated. 

"recon2v.cpp: In function ‘int main(int, char**)’:
recon2v.cpp:90:85: error: ‘reconstruct’ was not declared in this scope
   reconstruct(points2d, Ps_estimated, points3d_estimated, K_estimated, is_projective); "

**Comment by alalek** [comment] 2016-09-20 10:03
Looks like it is duplicate of #779

**Closed by alalek** 2016-09-20 10:03 UTC
Labels: duplicate
