### ISSUE TITLE
OpenCV Error: Assertion failed in cv::fastFree

### ISSUE THREAD

**Issue by harshdtu** [opencv/opencv_contrib#844] opened 2016-11-07 15:53 UTC
##### System information (version)

- OpenCV => master
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2013

##### Detailed description

OpenCV Error: Assertion failed (udata < (uchar*)ptr && ((uchar*)ptr - udata) <=
(ptrdiff_t)(sizeof(void*)+32)) in cv::fastFree, file D:\opencv-3.0\source\opencv
\modules\core\src\alloc.cpp, line 78

##### Steps to reproduce
I am using the textdetection.cpp from 
\opencv_contrib\modules\text\samples

I only converted the image to gray-scale before applying the ERFilters

**Comment by alalek** [comment] 2016-11-07 16:18
Probably duplicate of issue #841

**Comment by harshdtu** [comment] 2016-11-08 16:28
I am sorry, I am using the master branch, so shouldn't it have the mentioned changes already? I am new to git. What should I do?

**Comment by sovrasov** [comment] 2016-11-14 07:58
Resolved in #848

**Closed by sovrasov** 2016-11-14 07:58 UTC
