### ISSUE TITLE
opencv_contrib\modules\rgbd\src\dynafu.cpp has err.

### ISSUE THREAD

**Issue by r9kawai** [opencv/opencv_contrib#2334] opened 2019-11-07 04:32 UTC
I report below compile err and amend example.

- OpenCV => 4.1.2-dev
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description
[opencv_contrib\modules\rgbd\src\dynafu.cpp]
It source has syntax err. (234)
> float f[params.frameSize.width * params.frameSize.height];
> float pixels[params.frameSize.width * params.frameSize.height][3];

these are non fixed length array.

##### Steps to reproduce
>  #if 1	// AMEND
>  	float *f = new float[params.frameSize.width * params.frameSize.height];
>  	float *pixels = new float[params.frameSize.width * params.frameSize.height * 3];
>  	glReadPixels(0, 0, params.frameSize.width, params.frameSize.height, GL_DEPTH_COMPONENT, GL_FLOAT, f);
>  	glReadPixels(0, 0, params.frameSize.width, params.frameSize.height, GL_RGB, GL_FLOAT, pixels);
>  #else
>  	float f[params.frameSize.width * params.frameSize.height];
>  	float pixels[params.frameSize.width * params.frameSize.height][3];
>      glReadPixels(0, 0, params.frameSize.width, params.frameSize.height, GL_DEPTH_COMPONENT, GL_FLOAT, &f[0]);
>      glReadPixels(0, 0, params.frameSize.width, params.frameSize.height, GL_RGB, GL_FLOAT, &pixels[0][0]);
>  #endif

...

>  #if 1	// AMEND
>  	delete[] pixels;
>  	delete[] f;
>  #endif
>  #else
>      CV_UNUSED(depthImage);
>      CV_UNUSED(shadedImage);
>      NO_OGL_ERR;
>  #endif
>  }

What do you think about above?

**Comment by alalek** [comment] 2019-11-07 07:54
duplicate of #2307

It is better to propose patches through pull requests.

> new / delete[]

Please avoid manual memory allocations. Use `std::vector` instead.

**Closed by alalek** 2019-11-07 07:54 UTC
Labels: category: rgbd, duplicate
