### ISSUE TITLE
when use detect.caffemodel sr.caffemodel ios app will crash

### ISSUE THREAD

**Issue by MichaelHuyp** [opencv/opencv_contrib#2932] opened 2021-04-27 03:05 UTC
````swift
        let detector_prototxt_path = Bundle.main.path(forResource: "detect.prototxt", ofType: nil)
        let detector_caffe_model_path = Bundle.main.path(forResource: "detect.caffemodel", ofType: nil)
        let super_resolution_prototxt_path = Bundle.main.path(forResource: "sr.prototxt", ofType: nil)
        let super_resolution_caffe_model_path = Bundle.main.path(forResource: "sr.caffemodel", ofType: nil)
        
        let detector = WeChatQRCode(detector_prototxt_path: detector_prototxt_path ?? "", detector_caffe_model_path: detector_caffe_model_path ?? "", super_resolution_prototxt_path: super_resolution_prototxt_path ?? "", super_resolution_caffe_model_path: "")
````

terminating with uncaught exception of type cv::Exception: OpenCV(4.5.2) /Users/huyunpeng/Desktop/opencv/opencv-4.5.2/modules/core/src/utils/filesystem.cpp:580: error: (-213:The function/feature is not implemented)  in function 'exists'

@dddzg

**Comment by dddzg** [comment] 2021-04-27 03:24
It seems like that the file is not existed? Could you
check it further?

**Comment by MichaelHuyp** [comment] 2021-04-27 06:15
![image](https://user-images.githubusercontent.com/12581809/116194032-db21ef80-a762-11eb-9c56-f11ee70869b2.png)
![image](https://user-images.githubusercontent.com/12581809/116194080-ec6afc00-a762-11eb-8264-58b995348ebb.png)
I am not sure if it is caused by the too high version of opencv

**Comment by dddzg** [comment] 2021-04-27 06:36
As far as I observe, for wechat qrcode module, it will check the file existence by 
https://github.com/opencv/opencv_contrib/blob/ff9b0a10f659667cc2bb52592920770f55eb6134/modules/wechat_qrcode/src/wechat_qrcode.cpp#L72
The problems seem to be caused by the not implemented function `exists` in ios.
I have no ideas because the ios code is generated automatically by opencv.
Do you have any ideas @alalek ?

Moreover, our code has passed the opencv pre-commit checking tools (including ios check) before merged into opencv.(https://pullrequest.opencv.org/#/summary/contrib)
So, you would better check theenvironment again.
A feasible solution is removing these lines (`utils::fs::exists`) and re-compling the wechat qrcode module.

**Comment by MichaelHuyp** [comment] 2021-04-27 07:58
thanks!
The program can run very well when remove CV_Assert(utils::fs::exists)
![image](https://user-images.githubusercontent.com/12581809/116206448-63a78c80-a771-11eb-86e7-55a8e771fda1.png)

**Closed** 2021-04-27 08:52 UTC
