### ISSUE TITLE
Run-Time Error Importing Caffe Models

### ISSUE THREAD

**Issue by stephaniebosshard** [opencv/opencv_contrib#749] opened 2016-08-16 08:09 UTC
Someone else is also having the same issues here is the link: http://stackoverflow.com/questions/38877316/opencv3-1dnn-unhandled-exception/38968708#38968708

Link to previous question: http://answers.opencv.org/question/100317/run-time-error-importing-caffe-models/ 

System Information:
Open CV=>3.1
OS => Windows64 Bit
Complier=>Visual Studio 2013

Detailed description:

When importing a caffe model I am getting the error convolution_layer.cpp:89:error:(-215) input.dims() ==4 && (input.type() == CV_32F || input.type() == CV_64F) in function cv::dnn::ConvolutionLayerImpl::allocate.

We never used to have this problem until recently we have rebuilt the libaries multiple times. We have had the program sucessfully run for quite some time importing and classifying with caffe models. However we lost the origional copies and as we reconstructed the new libaries this error has occured. 

Steps to reproduce:

This particular code is run in a service and was 100% working before the change in libaries. I found that 
 the excpetion is thrown when creating the input Blob.
    
```
//Attempt to import model and catch error if it fails
	try
	{
		importer = dnn::createCaffeImporter(modelTxt, modelBin);
	}
	catch (const cv::Exception &err)
	{
		//std::cerr << err.msg + "\n" << std::endl;
		std::string errors = alreadyScanned.getClientName() + ":" + alreadyScanned.getSchool() + ":Failed To import model, Please check detection.cpp";
		const char* error = errors.c_str();
		tcp.sendMessage(error, REPORT_IP, REPORT_PORT);
	}

	//Catch all errors
	//TODO INCLUDE LOGGER TO WRITE ERRORS IF THERE IS FAILURE.
	if (!importer)
	{
		std::cerr << "Can't load network by using the following files: " << std::endl;
		std::cerr << "prototxt:   " << modelTxt << std::endl;
		std::cerr << "caffemodel: " << modelBin << std::endl;
		exit(-1);
	}


	dnn::Net net;
	importer->populateNet(net);

	//Clear importer from memory
	importer.release();
	int counter = 0;

	//Loop Through images
	for (auto it = begin(imageFilePaths); it != end(imageFilePaths); it++)
	{
		//Check to see if service has been asked to stop
		if (WaitForSingleObject(SCM.getStopEvent(), 0) == WAIT_OBJECT_0)
		{
			SCM.stopService();
			break;
		}


		//Store Current Image to scan
		string imageFile = *it;

		
		Mat img = imread(imageFile);

		//Check to see if valid image
		//TODO NEED TO INCLUDE LOGGER TO WRITE ERRORS IF THERE IS FAILURE
		//Catch Image Error
		if (!img.empty())
		{

			
			resize(img, img, Size(224, 224));       //Control the resizing of images if nessesary
			dnn::Blob inputBlob = dnn::Blob(img);   //THIS LINE HERE IS WHERE THE CODE FAILS AND THROWS EXCEPTION
			net.setBlob(".data", inputBlob);        //set the network input
			net.forward();                          //compute output
			dnn::Blob prob = net.getBlob("prob");   //gather output of "prob" layer
			int classId;
			double classProb;

			//Find the Highest probability class
			getMaxClass(prob, &classId, &classProb);
```
Thank you for taking a look at this.

**Comment by stephaniebosshard** [comment] 2016-08-17 10:57
Hey I just went an reconstructed the old libaries and with the exact same code provided it worked fine. So I think its a problem with the libaries.

**Comment by mshabunin** [comment] 2016-08-19 09:21
I guess we can close it.

**Closed by mshabunin** 2016-08-19 09:21 UTC
Labels: invalid

**Comment by cnsgcu** [comment] 2016-09-11 06:55
I ran into this issue with the new version of OpenCV. The problem is that the Blob constructor no longer creates 4 dims arrays from source images.
```C++
// broken in new version
dnn::Blob inputBlob = dnn::Blob(img);
```
Please use [cv::dnn::Blob.fromImage(img)](https://github.com/opencv/opencv_contrib/blob/master/modules/dnn/include/opencv2/dnn/blob.hpp#L157).

```C++
// Constucts 4-dimensional blob (so-called batch) from image or array of images.
dnn::Blob inputBlob = dnn::Blob::fromImages(img);
```
